sudo: required

env:
 matrix:
  - DOCKER_IMAGE=ubuntu.18.04
  - DOCKER_IMAGE=centos.7

language: c

language: java
jdk: openjdk8

services:
 - docker

script:
 - docker build -f utils/docker/Dockerfile.$DOCKER_IMAGE -t daos/$DOCKER_IMAGE --build-arg NOBUILD=1 --build-arg UID=$UID .
 - docker run -v $PWD:/home/daos/daos:z daos/$DOCKER_IMAGE /bin/bash -c "scons --build-deps=yes install"
