// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pool.proto

package mgmt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PoolCreateReq supplies new pool parameters.
type PoolCreateReq struct {
	Scmbytes             uint64   `protobuf:"varint,1,opt,name=scmbytes,proto3" json:"scmbytes,omitempty"`
	Nvmebytes            uint64   `protobuf:"varint,2,opt,name=nvmebytes,proto3" json:"nvmebytes,omitempty"`
	Ranks                string   `protobuf:"bytes,3,opt,name=ranks,proto3" json:"ranks,omitempty"`
	Numsvcreps           uint32   `protobuf:"varint,4,opt,name=numsvcreps,proto3" json:"numsvcreps,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Usergroup            string   `protobuf:"bytes,6,opt,name=usergroup,proto3" json:"usergroup,omitempty"`
	Uuid                 string   `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sys                  string   `protobuf:"bytes,8,opt,name=sys,proto3" json:"sys,omitempty"`
	Acl                  []string `protobuf:"bytes,9,rep,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolCreateReq) Reset()         { *m = PoolCreateReq{} }
func (m *PoolCreateReq) String() string { return proto.CompactTextString(m) }
func (*PoolCreateReq) ProtoMessage()    {}
func (*PoolCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{0}
}
func (m *PoolCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolCreateReq.Unmarshal(m, b)
}
func (m *PoolCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolCreateReq.Marshal(b, m, deterministic)
}
func (dst *PoolCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolCreateReq.Merge(dst, src)
}
func (m *PoolCreateReq) XXX_Size() int {
	return xxx_messageInfo_PoolCreateReq.Size(m)
}
func (m *PoolCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoolCreateReq proto.InternalMessageInfo

func (m *PoolCreateReq) GetScmbytes() uint64 {
	if m != nil {
		return m.Scmbytes
	}
	return 0
}

func (m *PoolCreateReq) GetNvmebytes() uint64 {
	if m != nil {
		return m.Nvmebytes
	}
	return 0
}

func (m *PoolCreateReq) GetRanks() string {
	if m != nil {
		return m.Ranks
	}
	return ""
}

func (m *PoolCreateReq) GetNumsvcreps() uint32 {
	if m != nil {
		return m.Numsvcreps
	}
	return 0
}

func (m *PoolCreateReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PoolCreateReq) GetUsergroup() string {
	if m != nil {
		return m.Usergroup
	}
	return ""
}

func (m *PoolCreateReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PoolCreateReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

func (m *PoolCreateReq) GetAcl() []string {
	if m != nil {
		return m.Acl
	}
	return nil
}

// PoolCreateResp returns created pool uuid and ranks.
type PoolCreateResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Svcreps              string   `protobuf:"bytes,2,opt,name=svcreps,proto3" json:"svcreps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolCreateResp) Reset()         { *m = PoolCreateResp{} }
func (m *PoolCreateResp) String() string { return proto.CompactTextString(m) }
func (*PoolCreateResp) ProtoMessage()    {}
func (*PoolCreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{1}
}
func (m *PoolCreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolCreateResp.Unmarshal(m, b)
}
func (m *PoolCreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolCreateResp.Marshal(b, m, deterministic)
}
func (dst *PoolCreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolCreateResp.Merge(dst, src)
}
func (m *PoolCreateResp) XXX_Size() int {
	return xxx_messageInfo_PoolCreateResp.Size(m)
}
func (m *PoolCreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolCreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_PoolCreateResp proto.InternalMessageInfo

func (m *PoolCreateResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PoolCreateResp) GetSvcreps() string {
	if m != nil {
		return m.Svcreps
	}
	return ""
}

// PoolDestroyReq supplies pool identifier and force flag.
type PoolDestroyReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sys                  string   `protobuf:"bytes,2,opt,name=sys,proto3" json:"sys,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolDestroyReq) Reset()         { *m = PoolDestroyReq{} }
func (m *PoolDestroyReq) String() string { return proto.CompactTextString(m) }
func (*PoolDestroyReq) ProtoMessage()    {}
func (*PoolDestroyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{2}
}
func (m *PoolDestroyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolDestroyReq.Unmarshal(m, b)
}
func (m *PoolDestroyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolDestroyReq.Marshal(b, m, deterministic)
}
func (dst *PoolDestroyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDestroyReq.Merge(dst, src)
}
func (m *PoolDestroyReq) XXX_Size() int {
	return xxx_messageInfo_PoolDestroyReq.Size(m)
}
func (m *PoolDestroyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDestroyReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDestroyReq proto.InternalMessageInfo

func (m *PoolDestroyReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PoolDestroyReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

func (m *PoolDestroyReq) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// PoolDestroyResp returns resultant state of destroy operation.
type PoolDestroyResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolDestroyResp) Reset()         { *m = PoolDestroyResp{} }
func (m *PoolDestroyResp) String() string { return proto.CompactTextString(m) }
func (*PoolDestroyResp) ProtoMessage()    {}
func (*PoolDestroyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{3}
}
func (m *PoolDestroyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolDestroyResp.Unmarshal(m, b)
}
func (m *PoolDestroyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolDestroyResp.Marshal(b, m, deterministic)
}
func (dst *PoolDestroyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDestroyResp.Merge(dst, src)
}
func (m *PoolDestroyResp) XXX_Size() int {
	return xxx_messageInfo_PoolDestroyResp.Size(m)
}
func (m *PoolDestroyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDestroyResp.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDestroyResp proto.InternalMessageInfo

func (m *PoolDestroyResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// ListPoolsReq represents a request to list pools on a given DAOS system.
type ListPoolsReq struct {
	Sys                  string   `protobuf:"bytes,1,opt,name=sys,proto3" json:"sys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsReq) Reset()         { *m = ListPoolsReq{} }
func (m *ListPoolsReq) String() string { return proto.CompactTextString(m) }
func (*ListPoolsReq) ProtoMessage()    {}
func (*ListPoolsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{4}
}
func (m *ListPoolsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsReq.Unmarshal(m, b)
}
func (m *ListPoolsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsReq.Marshal(b, m, deterministic)
}
func (dst *ListPoolsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsReq.Merge(dst, src)
}
func (m *ListPoolsReq) XXX_Size() int {
	return xxx_messageInfo_ListPoolsReq.Size(m)
}
func (m *ListPoolsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsReq proto.InternalMessageInfo

func (m *ListPoolsReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

// ListPoolsResp returns the list of pools in the system.
type ListPoolsResp struct {
	Status               int32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Pools                []*ListPoolsResp_Pool `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListPoolsResp) Reset()         { *m = ListPoolsResp{} }
func (m *ListPoolsResp) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResp) ProtoMessage()    {}
func (*ListPoolsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{5}
}
func (m *ListPoolsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResp.Unmarshal(m, b)
}
func (m *ListPoolsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResp.Marshal(b, m, deterministic)
}
func (dst *ListPoolsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResp.Merge(dst, src)
}
func (m *ListPoolsResp) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResp.Size(m)
}
func (m *ListPoolsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResp proto.InternalMessageInfo

func (m *ListPoolsResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListPoolsResp) GetPools() []*ListPoolsResp_Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

type ListPoolsResp_Pool struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Svcreps              string   `protobuf:"bytes,2,opt,name=svcreps,proto3" json:"svcreps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsResp_Pool) Reset()         { *m = ListPoolsResp_Pool{} }
func (m *ListPoolsResp_Pool) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResp_Pool) ProtoMessage()    {}
func (*ListPoolsResp_Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_35ddf4b8d30b2aca, []int{5, 0}
}
func (m *ListPoolsResp_Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResp_Pool.Unmarshal(m, b)
}
func (m *ListPoolsResp_Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResp_Pool.Marshal(b, m, deterministic)
}
func (dst *ListPoolsResp_Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResp_Pool.Merge(dst, src)
}
func (m *ListPoolsResp_Pool) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResp_Pool.Size(m)
}
func (m *ListPoolsResp_Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResp_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResp_Pool proto.InternalMessageInfo

func (m *ListPoolsResp_Pool) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListPoolsResp_Pool) GetSvcreps() string {
	if m != nil {
		return m.Svcreps
	}
	return ""
}

func init() {
	proto.RegisterType((*PoolCreateReq)(nil), "mgmt.PoolCreateReq")
	proto.RegisterType((*PoolCreateResp)(nil), "mgmt.PoolCreateResp")
	proto.RegisterType((*PoolDestroyReq)(nil), "mgmt.PoolDestroyReq")
	proto.RegisterType((*PoolDestroyResp)(nil), "mgmt.PoolDestroyResp")
	proto.RegisterType((*ListPoolsReq)(nil), "mgmt.ListPoolsReq")
	proto.RegisterType((*ListPoolsResp)(nil), "mgmt.ListPoolsResp")
	proto.RegisterType((*ListPoolsResp_Pool)(nil), "mgmt.ListPoolsResp.Pool")
}

func init() { proto.RegisterFile("pool.proto", fileDescriptor_pool_35ddf4b8d30b2aca) }

var fileDescriptor_pool_35ddf4b8d30b2aca = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x95, 0x9b, 0xa4, 0x3f, 0xf3, 0x7d, 0x05, 0x64, 0x55, 0xc8, 0xaa, 0x10, 0x8a, 0xb2, 0x0a,
	0x9b, 0x2c, 0x80, 0x13, 0x00, 0xcb, 0x2e, 0x90, 0x6f, 0x90, 0xa6, 0xa6, 0xaa, 0x48, 0xea, 0xe0,
	0xb1, 0x2b, 0xf5, 0x10, 0x1c, 0x94, 0x5b, 0xa0, 0xb1, 0xfb, 0x93, 0x0a, 0xca, 0xca, 0x7e, 0x6f,
	0xfe, 0xde, 0x1b, 0x0d, 0x40, 0xab, 0x75, 0x5d, 0xb4, 0x46, 0x5b, 0xcd, 0xe3, 0x66, 0xd9, 0xd8,
	0xec, 0x8b, 0xc1, 0xf8, 0x55, 0xeb, 0xfa, 0xd9, 0xa8, 0xd2, 0x2a, 0xa9, 0x3e, 0xf8, 0x14, 0x86,
	0x58, 0x35, 0xf3, 0xad, 0x55, 0x28, 0x58, 0xca, 0xf2, 0x58, 0x1e, 0x30, 0xbf, 0x81, 0xd1, 0x7a,
	0xd3, 0xa8, 0x10, 0xec, 0xf9, 0xe0, 0x91, 0xe0, 0x13, 0x48, 0x4c, 0xb9, 0x7e, 0x47, 0x11, 0xa5,
	0x2c, 0x1f, 0xc9, 0x00, 0xf8, 0x2d, 0xc0, 0xda, 0x35, 0xb8, 0xa9, 0x8c, 0x6a, 0x51, 0xc4, 0x29,
	0xcb, 0xc7, 0xb2, 0xc3, 0x70, 0x0e, 0xb1, 0x43, 0x65, 0x44, 0xe2, 0x8b, 0xfc, 0x9f, 0xe6, 0xd0,
	0xbb, 0x34, 0xda, 0xb5, 0xa2, 0xef, 0x03, 0x47, 0xc2, 0x57, 0xb8, 0xd5, 0x42, 0x0c, 0x76, 0x15,
	0x6e, 0xb5, 0xe0, 0x57, 0x10, 0xe1, 0x16, 0xc5, 0xd0, 0x53, 0xf4, 0x25, 0xa6, 0xac, 0x6a, 0x31,
	0x4a, 0x23, 0x62, 0xca, 0xaa, 0xce, 0x9e, 0xe0, 0xa2, 0x6b, 0x15, 0x5b, 0x7e, 0x0d, 0x7d, 0xb4,
	0xa5, 0x75, 0xc1, 0x69, 0x22, 0x77, 0x88, 0x0b, 0x18, 0xec, 0x05, 0xf7, 0x7c, 0xc7, 0x3d, 0xcc,
	0x66, 0xa1, 0xc7, 0x8b, 0x42, 0x6b, 0xf4, 0x96, 0xf6, 0xb5, 0x57, 0xc3, 0x7e, 0xaa, 0xe9, 0x1d,
	0xd5, 0x4c, 0x20, 0x79, 0xd3, 0xa6, 0x52, 0x7e, 0x37, 0x43, 0x19, 0x40, 0x76, 0x07, 0x97, 0x27,
	0xdd, 0xce, 0x4b, 0xca, 0x52, 0xf8, 0x3f, 0x5b, 0xa1, 0xa5, 0x74, 0xa4, 0xb1, 0xbb, 0x11, 0xec,
	0x30, 0x22, 0xfb, 0x64, 0x30, 0xee, 0xa4, 0xfc, 0x61, 0xaf, 0x80, 0x84, 0x0e, 0x81, 0x04, 0x46,
	0xf9, 0xbf, 0x7b, 0x51, 0xd0, 0x29, 0x14, 0x27, 0xb5, 0x05, 0xfd, 0x64, 0x48, 0x9b, 0x3e, 0x42,
	0x4c, 0xf0, 0x57, 0xab, 0x67, 0x57, 0x35, 0xef, 0xfb, 0x3b, 0x7b, 0xf8, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x01, 0xd9, 0x45, 0x75, 0x02, 0x00, 0x00,
}
